/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cashreport;

/**
 *
 * @author johntor81
 */
public class LaporanKeuangan extends javax.swing.JFrame {

    /**
     * Creates new form LaporanKeuangan
     */
    public LaporanKeuangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laporan_panel = new javax.swing.JPanel();
        side_bar = new javax.swing.JPanel();
        dashboard_button = new javax.swing.JButton();
        laporan_button = new javax.swing.JButton();
        pendapatan_button = new javax.swing.JButton();
        pengeluaran_button = new javax.swing.JButton();
        main_content_laporan = new javax.swing.JPanel();
        header_laporan = new javax.swing.JLabel();
        starting_date = new com.toedter.calendar.JCalendar();
        starting_date2 = new com.toedter.calendar.JCalendar();
        starting_date_header = new javax.swing.JLabel();
        starting_date_header1 = new javax.swing.JLabel();
        right_panel = new javax.swing.JPanel();
        starting_date_field = new javax.swing.JTextField();
        starting_date_field1 = new javax.swing.JTextField();
        create_laporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side_bar.setBackground(new java.awt.Color(2, 62, 138));
        side_bar.setToolTipText("");

        dashboard_button.setBackground(new java.awt.Color(166, 179, 208));
        dashboard_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        dashboard_button.setText("DASHBOARD");
        dashboard_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_buttonActionPerformed(evt);
            }
        });

        laporan_button.setBackground(new java.awt.Color(225, 229, 240));
        laporan_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        laporan_button.setText("LAPORAN");
        laporan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_buttonActionPerformed(evt);
            }
        });

        pendapatan_button.setBackground(new java.awt.Color(166, 179, 208));
        pendapatan_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        pendapatan_button.setText("PENDAPATAN");
        pendapatan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendapatan_buttonActionPerformed(evt);
            }
        });

        pengeluaran_button.setBackground(new java.awt.Color(166, 179, 208));
        pengeluaran_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        pengeluaran_button.setText("PENGELUARAN");
        pengeluaran_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaran_buttonActionPerformed(evt);
            }
        });

        main_content_laporan.setBackground(new java.awt.Color(202, 240, 248));

        header_laporan.setFont(new java.awt.Font("JetBrainsMono NFM", 1, 36)); // NOI18N
        header_laporan.setText("Laporan Keuangan");

        starting_date.setBackground(new java.awt.Color(0, 150, 199));

        starting_date2.setBackground(new java.awt.Color(0, 150, 199));

        starting_date_header.setFont(new java.awt.Font("JetBrainsMono NFM Medium", 0, 12)); // NOI18N
        starting_date_header.setText("Ending Date");

        starting_date_header1.setFont(new java.awt.Font("JetBrainsMono NFM Medium", 0, 12)); // NOI18N
        starting_date_header1.setText("Starting Date");

        right_panel.setBackground(new java.awt.Color(0, 119, 182));

        starting_date_field.setText("Starting Date");
        starting_date_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starting_date_fieldActionPerformed(evt);
            }
        });

        starting_date_field1.setText("Ending Date");
        starting_date_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starting_date_field1ActionPerformed(evt);
            }
        });

        create_laporan.setFont(new java.awt.Font("JetBrainsMono NFM", 1, 17)); // NOI18N
        create_laporan.setText("Generate .pdf");
        create_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_laporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
        right_panel.setLayout(right_panelLayout);
        right_panelLayout.setHorizontalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(starting_date_field)
                    .addComponent(starting_date_field1))
                .addContainerGap())
            .addGroup(right_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(create_laporan)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        right_panelLayout.setVerticalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(starting_date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(starting_date_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(create_laporan)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout main_content_laporanLayout = new javax.swing.GroupLayout(main_content_laporan);
        main_content_laporan.setLayout(main_content_laporanLayout);
        main_content_laporanLayout.setHorizontalGroup(
            main_content_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_content_laporanLayout.createSequentialGroup()
                .addGroup(main_content_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_content_laporanLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(header_laporan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_content_laporanLayout.createSequentialGroup()
                        .addContainerGap(61, Short.MAX_VALUE)
                        .addGroup(main_content_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(main_content_laporanLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(starting_date_header))
                            .addGroup(main_content_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(starting_date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(starting_date, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(main_content_laporanLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(starting_date_header1)))
                        .addGap(56, 56, 56)))
                .addComponent(right_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        main_content_laporanLayout.setVerticalGroup(
            main_content_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_content_laporanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(header_laporan)
                .addGap(18, 18, 18)
                .addComponent(starting_date_header1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(starting_date, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(starting_date_header, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(starting_date2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout side_barLayout = new javax.swing.GroupLayout(side_bar);
        side_bar.setLayout(side_barLayout);
        side_barLayout.setHorizontalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_barLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengeluaran_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendapatan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboard_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(main_content_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        side_barLayout.setVerticalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_barLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard_button)
                .addGap(18, 18, 18)
                .addComponent(laporan_button)
                .addGap(18, 18, 18)
                .addComponent(pendapatan_button)
                .addGap(18, 18, 18)
                .addComponent(pengeluaran_button)
                .addGap(122, 122, 122))
            .addComponent(main_content_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout laporan_panelLayout = new javax.swing.GroupLayout(laporan_panel);
        laporan_panel.setLayout(laporan_panelLayout);
        laporan_panelLayout.setHorizontalGroup(
            laporan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporan_panelLayout.createSequentialGroup()
                .addComponent(side_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        laporan_panelLayout.setVerticalGroup(
            laporan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporan_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporan_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboard_buttonActionPerformed

    private void laporan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporan_buttonActionPerformed

    private void pendapatan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendapatan_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendapatan_buttonActionPerformed

    private void pengeluaran_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaran_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengeluaran_buttonActionPerformed

    private void create_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_laporanActionPerformed

    private void starting_date_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starting_date_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_starting_date_fieldActionPerformed

    private void starting_date_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starting_date_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_starting_date_field1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanKeuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_laporan;
    private javax.swing.JButton dashboard_button;
    private javax.swing.JLabel header_laporan;
    private javax.swing.JButton laporan_button;
    private javax.swing.JPanel laporan_panel;
    private javax.swing.JPanel main_content_laporan;
    private javax.swing.JButton pendapatan_button;
    private javax.swing.JButton pengeluaran_button;
    private javax.swing.JPanel right_panel;
    private javax.swing.JPanel side_bar;
    private com.toedter.calendar.JCalendar starting_date;
    private com.toedter.calendar.JCalendar starting_date2;
    private javax.swing.JTextField starting_date_field;
    private javax.swing.JTextField starting_date_field1;
    private javax.swing.JLabel starting_date_header;
    private javax.swing.JLabel starting_date_header1;
    // End of variables declaration//GEN-END:variables
}
