/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cashreport;

/**
 *
 * @author johntor81
 */
public class PendapatanKeuangan extends javax.swing.JFrame {

    /**
     * Creates new form PendapatanKeuangan
     */
    public PendapatanKeuangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendapatan_panel = new javax.swing.JPanel();
        side_bar = new javax.swing.JPanel();
        dashboard_button = new javax.swing.JButton();
        laporan_button = new javax.swing.JButton();
        pendapatan_button = new javax.swing.JButton();
        pengeluaran_button = new javax.swing.JButton();
        main_content_pendapatan = new javax.swing.JPanel();
        header_pendapatan = new javax.swing.JLabel();
        scroll_tabel_keuangan_pendapatan = new javax.swing.JScrollPane();
        tabel_keuangan_pendapatan = new javax.swing.JTable();
        filter_box_pendapatan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side_bar.setBackground(new java.awt.Color(2, 62, 138));
        side_bar.setToolTipText("");

        dashboard_button.setBackground(new java.awt.Color(166, 179, 208));
        dashboard_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        dashboard_button.setText("DASHBOARD");
        dashboard_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_buttonActionPerformed(evt);
            }
        });

        laporan_button.setBackground(new java.awt.Color(166, 179, 208));
        laporan_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        laporan_button.setText("LAPORAN");
        laporan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_buttonActionPerformed(evt);
            }
        });

        pendapatan_button.setBackground(new java.awt.Color(225, 229, 240));
        pendapatan_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        pendapatan_button.setText("PENDAPATAN");
        pendapatan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendapatan_buttonActionPerformed(evt);
            }
        });

        pengeluaran_button.setBackground(new java.awt.Color(166, 179, 208));
        pengeluaran_button.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        pengeluaran_button.setText("PENGELUARAN");
        pengeluaran_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaran_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout side_barLayout = new javax.swing.GroupLayout(side_bar);
        side_bar.setLayout(side_barLayout);
        side_barLayout.setHorizontalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_barLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengeluaran_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendapatan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboard_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        side_barLayout.setVerticalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_barLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(dashboard_button)
                .addGap(18, 18, 18)
                .addComponent(laporan_button)
                .addGap(18, 18, 18)
                .addComponent(pendapatan_button)
                .addGap(18, 18, 18)
                .addComponent(pengeluaran_button)
                .addGap(122, 122, 122))
        );

        main_content_pendapatan.setBackground(new java.awt.Color(202, 240, 248));

        header_pendapatan.setFont(new java.awt.Font("JetBrainsMono NFM", 1, 36)); // NOI18N
        header_pendapatan.setText("Pendapatan Keuangan");

        tabel_keuangan_pendapatan.setBackground(new java.awt.Color(0, 119, 182));
        tabel_keuangan_pendapatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_tabel_keuangan_pendapatan.setViewportView(tabel_keuangan_pendapatan);

        filter_box_pendapatan.setBackground(new java.awt.Color(0, 119, 182));
        filter_box_pendapatan.setFont(new java.awt.Font("JetBrainsMonoNL NF Medium", 0, 17)); // NOI18N
        filter_box_pendapatan.setForeground(new java.awt.Color(255, 255, 255));
        filter_box_pendapatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly", "Yearly" }));
        filter_box_pendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_box_pendapatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_content_pendapatanLayout = new javax.swing.GroupLayout(main_content_pendapatan);
        main_content_pendapatan.setLayout(main_content_pendapatanLayout);
        main_content_pendapatanLayout.setHorizontalGroup(
            main_content_pendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_content_pendapatanLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(main_content_pendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_content_pendapatanLayout.createSequentialGroup()
                        .addGroup(main_content_pendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll_tabel_keuangan_pendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                            .addGroup(main_content_pendapatanLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(filter_box_pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(main_content_pendapatanLayout.createSequentialGroup()
                        .addComponent(header_pendapatan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        main_content_pendapatanLayout.setVerticalGroup(
            main_content_pendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_content_pendapatanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(header_pendapatan)
                .addGap(18, 18, 18)
                .addComponent(filter_box_pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scroll_tabel_keuangan_pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pendapatan_panelLayout = new javax.swing.GroupLayout(pendapatan_panel);
        pendapatan_panel.setLayout(pendapatan_panelLayout);
        pendapatan_panelLayout.setHorizontalGroup(
            pendapatan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendapatan_panelLayout.createSequentialGroup()
                .addComponent(side_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main_content_pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pendapatan_panelLayout.setVerticalGroup(
            pendapatan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_content_pendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendapatan_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendapatan_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboard_buttonActionPerformed

    private void laporan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporan_buttonActionPerformed

    private void pendapatan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendapatan_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendapatan_buttonActionPerformed

    private void pengeluaran_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaran_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengeluaran_buttonActionPerformed

    private void filter_box_pendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_box_pendapatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_box_pendapatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendapatanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendapatanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendapatanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendapatanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendapatanKeuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboard_button;
    private javax.swing.JComboBox<String> filter_box_pendapatan;
    private javax.swing.JLabel header_pendapatan;
    private javax.swing.JButton laporan_button;
    private javax.swing.JPanel main_content_pendapatan;
    private javax.swing.JButton pendapatan_button;
    private javax.swing.JPanel pendapatan_panel;
    private javax.swing.JButton pengeluaran_button;
    private javax.swing.JScrollPane scroll_tabel_keuangan_pendapatan;
    private javax.swing.JPanel side_bar;
    private javax.swing.JTable tabel_keuangan_pendapatan;
    // End of variables declaration//GEN-END:variables
}
